spring.application.name=hostel-management-system
spring.datasource.url=jdbc:mysql://localhost:3306/hostel_db
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=root123
=======
spring.datasource.password=1111
>>>>>>> origin/notification-service

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080